### ISSUE TITLE
Some progress trackers show "X/Y over NaN days"

### ISSUE THREAD

**Issue by axemtitanium** [ApkalluFalls/.com-feedback#3]
Haven't really figured out a pattern to why this is, but certain day trackers show "NaN days", even within the same category. The mouseover text seems to pull the correct dates so it's not clear why it's calculating the number of days as NaN for some but not others. https://puu.sh/vKWLM/a11325c3ce.jpg My character id is 326976 on Lodestone if this issue is specific to me.

**Comment by EdgeFayth** [comment]
I actually noticed this bug happens when the number of days is a 4 digits numbers (so >999 days).
Hope that helps the bug solving.

Fayth

**Comment by JamesDonnelly** [comment]
Thanks for reporting this. The issue was indeed caused by 4 digit numbers as @EdgeFayth assumed. I was performing number conversion _after_ formatting the string: `1000` was being converted to `"1,000"` (or `"1.000"` depending on region) and then being converted back to a number which failed.

This has now been resolved.
